export const GET_PLAY_SONG="GET_PLAY_SONG";
export const REMOVE_PLAY_SONG="REMOVE_PLAY_SONG";
export const GET_LIKE_SONG="GET_LIKE_SONG";
export const GET_GROUP_INFO="GET_GROUP_INFO";
export const GET_GROUP_SEARCH="GET_GROUP_SEARCH";
export const SHOW_FORM_CREATE_FILE="SHOW_FORM_CREATE_FILE";


export const GET_FETCH_API_SONGS_START="GET_FETCH_API_SONGS_START";
export const GET_FETCH_API_SONGS_SUCCESS="GET_FETCH_API_SONGS_SUCCESS";
export const GET_FETCH_API_SONGS_FAIL="GET_FETCH_API_SONGS_FAIL";