export const SEARCH_INPUT_SET="SEARCH_INPUT_SET";


export const SEARCH_FETCH_API_SONGS_START="SEARCH_FETCH_API_SONGS_START";
export const SEARCH_FETCH_API_SONGS_SUCCESS="SEARCH_FETCH_API_SONGS_SUCCESS";
export const SEARCH_FETCH_API_SONGS_FAIL="SEARCH_FETCH_API_SONGS_FAIL";