export const SET_NAME_FILE = "SET_NAME_FILE";
export const GET_CHOOSE_FILE = "GET_CHOOSE_FILE";

export const F_G_P_D_START = "F_G_P_D_START";
export const F_G_P_D_FAIL = "F_G_P_D_FAIL";

export const GET_FETCH_FILES_SUCCESS = "GET_FETCH_FILES_SUCCESS";

export const POST_FETCH_FILES_SUCCESS = "POST_FETCH_FILES_SUCCESS";

export const DELETE_FETCH_FILES_SUCCESS = "DELETE_FETCH_FILES_SUCCESS";
